version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: atm-postgres
    environment:
      POSTGRES_DB: atm_db
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atm_user -d atm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  atm-network:
    driver: bridge
