spring:
  application:
    name: spring-jpos-atm-server

  datasource:
    url: jdbc:postgresql://localhost:54322/bankdb
    username: bankuser
    password: bankpass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

  threads:
    virtual:
      enabled: true

server:
  port: 9090

jpos:
  server:
    port: 22222
    max-sessions: 100
    channel: org.jpos.iso.channel.ASCIIChannel
    packager: org.jpos.iso.packager.BASE24Packager

hsm:
  url: http://localhost:8080
  pin:
    encrypted-pin-block:
      endpoint: /api/hsm/pin/verify-with-translation
    pvv:
      endpoint: /api/hsm/pin/verify-with-pvv
    format: ISO_0
    # PIN encryption algorithm: TDES (field 52), AES_128 (field 123), or AES_256 (field 123)
    encryption-algorithm: AES_256
  mac:
    # MAC algorithm: AES_CMAC or HMAC_SHA256_TRUNCATED
    algorithm: AES_CMAC
    # Enable MAC verification for incoming messages
    verify-enabled: true
    # Enable MAC generation for outgoing responses
    generate-enabled: true
  connection:
    timeout: 5000
    read-timeout: 10000
  keys:
    # Bank UUID for key derivation context (matches HSM seed data ISS001)
    bank-uuid: 48a9e84c-ff57-4483-bf83-b255f34a6466
    # TSK master key for MAC operations (TSK-TRM-ISS001-ATM-001 from HSM seed data)
    # 32 bytes (256 bits) = 64 hex characters
    tsk-master-key: 3AC638783EF600FE5E25E8A2EE5B0D222EB810DDF64C3681DD11AFEFAF41614B
    # TPK master key for PIN operations (TPK-TRM-ISS001-ATM-001 from HSM seed data)
    # 32 bytes (256 bits) = 64 hex characters
    tpk-master-key: 246A31D729B280DD7FCDA3BB7F187ABFA1BB0811D7EF3D68FDCA63579F3748B0

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO
    com.example.atm: DEBUG
