spring:
  application:
    name: spring-jpos-atm-simulator

  datasource:
    url: jdbc:postgresql://localhost:5433/atm_db
    username: atm_user
    password: atm_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

jpos:
  channel:
    class: org.jpos.iso.channel.ASCIIChannel
    host: localhost
    port: 8000
    timeout: 30000
  packager:
    class: org.jpos.iso.packager.Base24Packager
  mux:
    name: atm-mux
  q2:
    deployDir: deploy

logging:
  level:
    com.example.atm: DEBUG
    org.jpos: INFO
    org.hibernate.SQL: DEBUG
