spring:
  application:
    name: spring-jpos-atm-simulator

  datasource:
    url: jdbc:postgresql://localhost:5433/atm_db
    username: atm_user
    password: atm_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 7070

jpos:
  channel:
    class: org.jpos.iso.channel.ASCIIChannel
    host: localhost
    port: 22222
    timeout: 30000
  packager:
    class: org.jpos.iso.packager.BASE24Packager
  mux:
    name: atm-mux

crypto:
  tmk:
    # Terminal Master Key (TMK) - used to encrypt/decrypt other keys during key exchange
    # This is a long-lived key that should be securely provisioned to the terminal
    key: "1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF"
  tpk:
    key: "246A31D729B280DD7FCDA3BB7F187ABFA1BB0811D7EF3D68FDCA63579F3748B0"
  tsk:
    key: "3AC638783EF600FE5E25E8A2EE5B0D222EB810DDF64C3681DD11AFEFAF41614B"
  bank:
    uuid: "48a9e84c-ff57-4483-bf83-b255f34a6466"

terminal:
  id: "ATM-001"
  institution:
    id: "TRM-ISS001"

logging:
  level:
    com.example.atm: DEBUG
    org.jpos: INFO
    org.hibernate.SQL: DEBUG
